export const errorPageStyles = {
  page: [
    "min-w-0",
    "w-full",
    "max-w-3xl",
    "bg-[var(--bg)]",
    "px-4",
    "py-8",
    "text-[var(--text-main)]",
    "sm:px-6",
  ],
  card: [
    "w-full",
  ],
  panel: [
    "rounded-[2rem]",
    "border",
    "border-[var(--line)]",
    "bg-white",
    "p-6",
    "text-center",
    "shadow-sm",
    "sm:p-10",
  ],
  eyebrow: [
    "block",
    "text-xs",
    "font-extrabold",
    "tracking-[0.22em]",
    "text-[var(--text-sub)]",
    "uppercase",
  ],
  title: [
    "mt-4",
    "text-3xl",
    "font-extrabold",
    "tracking-tight",
    "text-[var(--text-main)]",
    "sm:text-4xl",
  ],
  description: [
    "block",
    "mx-auto",
    "mt-4",
    "max-w-xl",
    "text-sm",
    "leading-6",
    "text-[var(--text-sub)]",
    "sm:text-base",
  ],
  actions: [
    "mt-8",
    "flex",
    "flex-col",
    "justify-center",
    "gap-3",
    "sm:flex-row",
  ],
} as const;
