name = "my-weather-bot"
main = "src/worker.ts"
compatibility_date = "2026-03-02"
keep_vars = false

[vars]
API_BASE_URL = "https://apis.data.go.kr/1360000/VilageFcstInfoService_2.0"
KAKAO_REST_API_BASE_URL = "https://dapi.kakao.com"
AIRKOREA_API_BASE_URL = "https://apis.data.go.kr/B552584/ArpltnInforInqireSvc"
RADAR_API_BASE_URL = "https://apihub.kma.go.kr/api/typ03/cgi/rdr"
RADAR_API_UPSTREAM_BASE_URL = "https://apihub.kma.go.kr/api/typ03/cgi/rdr"
RADAR_API_PROXY_PATH = "/api/radar"

[assets]
directory = "./dist"
binding = "ASSETS"
