export const bookmarkPageStyles = {
  page: ["space-y-6", "md:space-y-8"],
  hero: [
    "flex",
    "min-w-0",
    "flex-col",
    "gap-4",
    "sm:flex-row",
    "sm:items-end",
    "sm:justify-between",
  ],
  heroText: ["min-w-0"],
  eyebrow: [
    "text-sm",
    "font-extrabold",
    "tracking-[0.18em]",
    "text-[var(--text-sub)]",
    "uppercase",
  ],
  title: [
    "mt-2",
    "text-3xl",
    "font-extrabold",
    "tracking-[-0.04em]",
    "text-[var(--text-main)]",
    "md:text-4xl",
  ],
  description: ["mt-2", "break-words", "text-sm", "leading-6", "text-[var(--text-sub)]"],
  actionList: ["flex", "shrink-0", "items-center", "gap-3"],
  actionButton: ["gap-2", "whitespace-nowrap"],
  remainSlotWrap: [
    "flex",
    "items-center",
    "justify-between",
    "gap-2",
    "rounded-2xl",
    "border",
    "border-[var(--line)]",
    "bg-white",
    "px-4",
    "py-3",
    "shadow-sm",
  ],
  remainSlotContent: ["text-sm", "font-semibold", "text-[var(--text-main)]"],
  remainSlotHint: ["text-sm", "font-medium", "text-[var(--text-sub)]"],

  bookmarkListNodata: [
    "rounded-2xl",
    "border",
    "border-dashed",
    "border-[var(--line)]",
    "bg-[var(--surface)]",
    "px-5",
    "py-10",
    "text-center",
    "text-sm",
    "text-[var(--text-sub)]",
  ],

  bookmarkListWrap: ["grid", "grid-cols-2", "gap-4", "lg:grid-cols-3", "xl:grid-cols-4"],
  bookmarkCard: [
    "min-h-44",
    "rounded-[1.35rem]",
    "border",
    "border-[var(--line)]",
    "bg-white",
    "p-4",
    "shadow-sm",
    "transition",
    "cursor-pointer",
    "hover:shadow-md",
  ],
  bookmarkCardHeader: ["flex", "items-start", "justify-between", "gap-3"],
  bookmarkCardTitle: [
    "block",
    "text-lg",
    "font-extrabold",
    "leading-tight",
    "text-[var(--text-main)]",
    "sm:text-xl",
  ],
  bookmarkCardLocation: ["mt-1", "block", "text-xs", "text-[var(--text-sub)]", "sm:text-sm"],
  bookmarkCardTemp: ["block", "text-xs", "text-[var(--text-sub)]"],

  bookmarkCardCaption: [],
  bookmarkCardAction: ["mt-3", "flex", "items-center", "justify-end", "gap-2"],

  bookmarkMenuWrap: ["relative"],
  bookmarkMenuTrigger: [
    "h-8",
    "w-8",
    "rounded-xl",
    "border",
    "border-[var(--line)]",
    "bg-white",
    "text-lg",
    "leading-none",
    "text-[var(--text-sub)]",
    "transition",
    "cursor-pointer",
    "hover:bg-slate-100",
  ],
  bookmarkMenuPanel: [
    "absolute",
    "top-10",
    "right-0",
    "z-10",
    "w-32",
    "rounded-xl",
    "border",
    "border-[var(--line)]",
    "bg-white",
    "p-1",
    "shadow-lg",
  ],
  bookmarkMenuItem: [
    "w-full",
    "rounded-lg",
    "px-3",
    "py-2",
    "text-left",
    "text-sm",
    "font-semibold",
    "text-[var(--text-main)]",
    "transition",
    "cursor-pointer",
    "hover:bg-slate-100",
  ],
  bookmarkMenuItemDanger: [
    "w-full",
    "rounded-lg",
    "border",
    "border-red-300",
    "px-3",
    "py-2",
    "text-left",
    "text-sm",
    "font-semibold",
    "text-red-600",
    "transition",
    "cursor-pointer",
    "hover:bg-red-50",
  ],
  addCityCard: [
    "min-h-44",
    "rounded-[1.35rem]",
    "border",
    "border-dashed",
    "border-[var(--line)]",
    "bg-transparent",
    "p-4",
    "text-sm",
    "font-extrabold",
    "text-[var(--text-sub)]",
    "transition",
    "hover:bg-white",
    "hover:text-[var(--text-main)]",
  ],
  addCityIcon: [
    "mx-auto",
    "mb-3",
    "grid",
    "size-10",
    "place-items-center",
    "rounded-full",
    "border",
    "border-[var(--line)]",
    "text-2xl",
    "font-semibold",
  ],
  manageAlertsCard: [
    "flex",
    "w-full",
    "items-center",
    "gap-4",
    "rounded-[1.5rem]",
    "border",
    "border-dashed",
    "border-[var(--line)]",
    "bg-white/70",
    "p-5",
    "text-left",
    "transition",
    "hover:bg-white",
  ],
  manageAlertsIcon: [
    "grid",
    "size-12",
    "shrink-0",
    "place-items-center",
    "rounded-full",
    "bg-[var(--surface-soft)]",
    "text-[var(--text-sub)]",
  ],
  manageAlertsText: [
    "flex",
    "min-w-0",
    "flex-1",
    "flex-col",
    "gap-1",
    "text-sm",
    "text-[var(--text-sub)]",
  ],
  manageAlertsArrow: ["rotate-90", "text-[var(--text-sub)]"],
} as const;

export const bookmarkCurrentLocationStyles = {
  card: [
    "block",
    "w-full",
    "min-w-0",
    "rounded-[1.5rem]",
    "border",
    "border-[var(--line)]",
    "bg-white",
    "p-6",
    "text-left",
    "shadow-sm",
    "transition",
    "hover:shadow-md",
  ],
  fetching: ["animate-pulse"],
  header: ["flex", "items-start", "justify-between", "gap-4"],
  eyebrow: [
    "text-xs",
    "font-extrabold",
    "tracking-[0.18em]",
    "text-[var(--text-sub)]",
    "uppercase",
  ],
  title: [
    "mt-2",
    "break-words",
    "text-3xl",
    "font-extrabold",
    "tracking-[-0.04em]",
    "text-[var(--text-main)]",
    "sm:text-4xl",
  ],
  icon: ["h-14", "w-14", "text-[var(--text-main)]"],
  body: ["mt-10", "flex", "items-end", "justify-between", "gap-5", "sm:items-end"],
  temperature: [
    "text-7xl",
    "font-light",
    "tracking-[-0.08em]",
    "text-[var(--text-main)]",
    "sm:text-8xl",
  ],
  meta: [
    "flex",
    "shrink-0",
    "flex-col",
    "items-end",
    "gap-1",
    "text-base",
    "font-medium",
    "text-[var(--text-sub)]",
  ],
  placeholderText: ["mt-5", "break-words", "text-sm", "text-[var(--text-sub)]"],
} as const;

export const bookmarkEditStyles = {
  bookmarkEditForm: ["flex", "h-full", "flex-col", "justify-between", "gap-20"],
  bookmarkEditInput: [
    "w-full",
    "rounded-xl",
    "border",
    "border-[var(--line)]",
    "bg-white",
    "px-3",
    "py-2",
    "text-sm",
    "text-[var(--text-main)]",
    "outline-none",
    "ring-[var(--accent)]",
    "transition",
    "focus:ring-2",
  ],
  bookmarkEditButtonList: ["mt-4", "flex", "gap-2", "justify-end"],
  bookmarkEditSaveButton: [
    "rounded-xl",
    "bg-[var(--accent)]",
    "px-3",
    "py-2",
    "text-sm",
    "font-semibold",
    "text-white",
    "transition",
    "cursor-pointer",
    "hover:opacity-90",
  ],
  bookmarkEditCancleButton: [
    "rounded-xl",
    "border",
    "border-[var(--line)]",
    "bg-white",
    "px-3",
    "py-2",
    "text-sm",
    "font-semibold",
    "text-[var(--text-main)]",
    "transition",
    "cursor-pointer",
    "hover:bg-slate-50",
  ],
};

export const bookmarkSummaryStyles = {
  summaryWrap: ["mt-8", "flex", "flex-col", "gap-1"],
  summaryMainContent: ["text-3xl", "font-extrabold", "text-[var(--text-main)]", "sm:text-4xl"],
  summarySubContent: ["text-xs", "text-[var(--text-sub)]", "sm:text-sm"],
  summaryNodata: ["mt-2", "text-sm", "whitespace-pre-wrap"],
};
