export const mainPageStyles = {
  page: ["space-y-5", "md:space-y-6"],
  searchWrap: ["rounded-xl", "shadow-lg", "shadow-gray-500/25"],
  searchStatus: ["mt-2", "text-sm", "text-[var(--text-sub)]"],
  searchInput: [
    "w-full",
    "rounded-xl",
    "bg-[var(--surface)]",
    "px-4",
    "py-3",
    "text-sm",
    "outline-none",
    "ring-[var(--accent)]",
    "transition",
    "focus:ring-2",
  ],
  dailySummary: ["rounded-xl", "bg-white", "p-6", "shadow-lg", "shadow-gray-500/25"],
  dailySummarySub: ["mt-2", "text-blue-100"],
  section: [
    "mb-5",
    "rounded-2xl",
    "border",
    "border-[var(--line)]",
    "bg-[var(--surface)]",
    "p-4",
    "md:p-6",
  ],
  sectionTitle: "mb-3 text-sm font-bold tracking-wide text-[var(--text-sub)] uppercase",
} as const;

export const nowInfoCardStyles = {
  root: ["rounded-[1.75rem]", "bg-[var(--surface)]", "px-6", "py-7", "md:px-8", "md:py-8"],
  loading: ["text-sm", "text-[var(--text-sub)]"],
  error: ["text-sm", "text-[var(--danger)]"],
  header: ["flex", "flex-col", "gap-4", "md:flex-row", "md:items-start", "md:justify-between"],
  headerText: ["space-y-2"],
  titleRow: ["flex", "items-start", "gap-3"],
  titleGroup: ["min-w-0", "flex-1", "space-y-1"],
  mobileTitle: ["min-w-0", "space-y-1"],
  desktopTitle: ["min-w-0"],
  districtPrimary: [
    "block",
    "min-w-0",
    "text-4xl",
    "font-extrabold",
    "tracking-tight",
    "leading-[1.2]",
    "text-[var(--text-main)]",
  ],
  districtPrimaryAlias: ["truncate"],
  districtSecondary: ["truncate", "text-sm", "font-medium", "text-[var(--text-sub)]"],
  districtDesktop: [
    "block",
    "min-w-0",
    "text-5xl",
    "font-extrabold",
    "tracking-tight",
    "leading-[1.3]",
    "text-[var(--text-main)]",
  ],
  districtDesktopAlias: ["truncate"],
  districtLoading: ["animate-pulse", "transition-colors", "duration-300", "text-[var(--text-sub)]"],
  refreshButton: ["shrink-0"],
  refreshIconLoading: ["animate-spin"],
  date: ["text-lg", "text-[var(--text-sub)]", "md:text-xl"],
  weatherIcon: ["text-[var(--icon-subtle)]"],
  body: [
    "mt-10",
    "flex",
    "flex-col",
    "gap-4",
    "md:mt-14",
    "md:flex-row",
    "md:items-end",
    "md:gap-8",
  ],
  currentTemp: [
    "text-7xl",
    "font-extrabold",
    "leading-none",
    "tracking-[-0.04em]",
    "text-[var(--text-main)]",
    "md:text-9xl",
  ],
  currentMeta: ["space-y-2", "pb-2"],
  currentSummary: ["text-2xl", "font-semibold", "text-[var(--text-main)]", "md:text-3xl"],
  currentFeelsLike: ["text-xl", "text-[var(--text-muted)]", "md:text-2xl"],
  divider: ["my-10", "h-px", "w-full", "bg-[var(--line)]"],
  detailList: ["grid", "grid-cols-1", "gap-4", "md:grid-cols-3", "md:gap-6"],
  detailItem: ["flex", "items-center", "gap-4", "rounded-2xl", "px-1", "py-2"],
  detailIcon: ["text-[var(--icon-subtle)]"],
  detailText: ["flex", "flex-col", "gap-1"],
  detailLabel: [
    "text-xs",
    "font-bold",
    "tracking-[0.18em]",
    "text-[var(--text-muted)]",
    "uppercase",
    "md:text-sm",
  ],
  detailValue: ["text-2xl", "font-extrabold", "text-[var(--text-main)]", "md:text-3xl"],
} as const;

export const hourlyInfoCardStyles = {
  viewport: ["relative", "overflow-hidden"],
  wrapper: [
    "overflow-x-auto",
    "scrollbar-hide",
    "cursor-grab",
    "select-none",
    "active:cursor-grabbing",
    "-mx-4",
    "px-4",
  ],
  list: ["flex", "gap-3", "pb-1", "md:gap-4"],
  detail: [
    "flex",
    "w-24",
    "sm:w-28",
    "shrink-0",
    "flex-col",
    "items-center",
    "gap-4",
    "rounded-[1rem]",
    "border",
    "border-transparent",
    "bg-[var(--surface)]",
    "px-5",
    "py-4",
    "transition-all",
    "duration-200",
    "hover:bg-[var(--surface-soft)]",
    "hover:shadow-sm",
  ],
  detailHour: [
    "text-base",
    "font-semibold",
    "tracking-tight",
    "text-[var(--text-sub)]",
    "whitespace-nowrap",
  ],
  detailIcon: ["text-[var(--icon-subtle)]"],
  detailValue: ["text-2xl", "font-extrabold", "leading-none", "text-[var(--text-main)]"],
  loading: ["text-sm", "text-[var(--text-sub)]"],
  error: ["text-sm", "text-[var(--danger)]"],
};
