export const mainPageStyles = {
  page: ["w-full", "self-start", "space-y-5", "md:space-y-8"],
  searchWrap: [
    "rounded-2xl",
    "border",
    "border-[var(--line)]",
    "bg-white",
    "shadow-sm",
    "md:rounded-[1.5rem]",
  ],
  searchInput: [
    "w-full",
    "rounded-xl",
    "bg-[var(--surface)]",
    "px-4",
    "py-3",
    "text-sm",
    "outline-none",
    "ring-[var(--accent)]",
    "transition",
    "focus:ring-2",
  ],
  dailySummary: ["rounded-xl", "bg-white", "p-6", "shadow-lg", "shadow-gray-500/25"],
  dailySummarySub: ["mt-2", "text-blue-100"],
  dashboardGrid: [
    "grid",
    "min-w-0",
    "gap-6",
    "lg:grid-cols-[minmax(0,1fr)_22rem]",
    "lg:items-start",
  ],
  mainColumn: ["min-w-0", "space-y-5", "md:space-y-6"],
  section: [
    "min-w-0",
    "rounded-[1.5rem]",
    "border",
    "border-[var(--line)]",
    "bg-white",
    "p-4",
    "shadow-sm",
    "md:p-6",
  ],
  heroSection: ["p-0", "md:p-0"],
  sectionHeader: ["mb-4", "flex", "items-center", "justify-between", "gap-3"],
  sectionTitle: "text-sm font-extrabold tracking-[0.18em] text-[var(--text-sub)] uppercase",
  sectionActionText: [
    "shrink-0",
    "text-sm",
    "font-semibold",
    "text-[var(--text-main)]",
    "underline",
  ],
  sectionTitleFetching: [
    "animate-pulse",
    "transition-colors",
    "duration-300",
    "text-[var(--text-sub)]",
  ],
  metricGrid: ["grid", "gap-4", "sm:grid-cols-2", "xl:grid-cols-4"],
  metricCard: [
    "flex",
    "min-h-48",
    "min-w-0",
    "flex-col",
    "rounded-[1.5rem]",
    "border",
    "border-[var(--line)]",
    "bg-white",
    "p-5",
    "shadow-sm",
  ],
  metricHeader: [
    "flex",
    "min-h-[2.25rem]",
    "items-start",
    "justify-between",
    "gap-2",
    "text-xs",
    "font-extrabold",
    "tracking-[0.18em]",
    "text-[var(--text-sub)]",
    "uppercase",
    "leading-[1.35]",
  ],
  metricHeaderLabel: [
    "min-w-0",
    "line-clamp-2",
  ],
  metricGradeBadge: [
    "shrink-0",
    "rounded-full",
    "border",
    "px-2",
    "py-0.5",
    "text-[0.65rem]",
    "font-extrabold",
    "leading-4",
    "tracking-normal",
    "normal-case",
  ],
  metricGradeTone: {
    good: [
      "border-[var(--color-green-200)]",
      "bg-[var(--color-green-50)]",
      "text-[var(--color-green-700)]",
    ],
    normal: [
      "border-[var(--color-blue-200)]",
      "bg-[var(--color-blue-50)]",
      "text-[var(--color-blue-700)]",
    ],
    bad: [
      "border-[var(--color-amber-200)]",
      "bg-[var(--color-amber-50)]",
      "text-[var(--color-amber-700)]",
    ],
    veryBad: [
      "border-[var(--color-red-200)]",
      "bg-[var(--color-red-50)]",
      "text-[var(--color-red-700)]",
    ],
    unavailable: [
      "border-[var(--color-slate-200)]",
      "bg-[var(--color-slate-50)]",
      "text-[var(--text-sub)]",
    ],
  },
  metricValue: [
    "mt-6",
    "block",
    "text-4xl",
    "font-semibold",
    "tracking-[-0.04em]",
    "text-[var(--text-main)]",
  ],
  metricUnit: ["ml-1", "text-lg", "font-medium", "tracking-normal"],
  metricDescription: [
    "mt-auto",
    "break-words",
    "pt-4",
    "text-sm",
    "leading-6",
    "text-[var(--text-sub)]",
  ],
  mapCanvas: ["h-[21.875rem]"],
  locationDialogBackdrop: [
    "fixed",
    "inset-0",
    "z-50",
    "min-w-[var(--app-min-width)]",
    "flex",
    "items-end",
    "justify-center",
    "bg-black/35",
    "px-4",
    "py-4",
    "sm:items-center",
  ],
  locationDialogPanel: [
    "w-full",
    "max-w-lg",
    "rounded-[1.75rem]",
    "border",
    "border-[var(--line)]",
    "bg-white",
    "p-5",
    "shadow-xl",
    "sm:p-6",
  ],
  locationDialogTitle: [
    "text-2xl",
    "font-extrabold",
    "tracking-tight",
    "text-[var(--text-main)]",
  ],
  locationDialogDescription: [
    "block",
    "mt-3",
    "text-sm",
    "leading-6",
    "text-[var(--text-sub)]",
  ],
  locationDialogHint: [
    "block",
    "mt-4",
    "rounded-2xl",
    "bg-[var(--surface-soft)]",
    "p-4",
    "text-sm",
    "leading-6",
    "text-[var(--text-sub)]",
  ],
  locationDialogActions: [
    "mt-6",
    "grid",
    "gap-2",
    "sm:grid-cols-2",
  ],
} as const;

export const nowInfoCardStyles = {
  root: [
    "rounded-[1.5rem]",
    "bg-white",
    "px-6",
    "py-7",
    "md:rounded-[1.75rem]",
    "md:px-8",
    "md:py-8",
  ],
  loading: ["text-sm", "text-[var(--text-sub)]"],
  error: [
    "text-xl",
    "flex",
    "flex-col",
    "items-center",
    "justify-center",
    "gap-3",
    "md:gap-10",
    "md:flex-row",
  ],
  header: [
    "flex",
    "flex-col",
    "items-center",
    "gap-4",
    "text-center",
    "md:flex-row",
    "md:items-start",
    "md:justify-between",
    "md:text-left",
  ],
  headerText: ["min-w-0", "max-w-full", "space-y-2", "md:flex-1"],
  titleRow: ["flex", "min-w-0", "items-start", "gap-3"],
  titleGroup: ["min-w-0", "flex-1", "space-y-1"],
  mobileTitle: ["min-w-0", "max-w-full", "space-y-1"],
  desktopTitle: ["min-w-0", "max-w-full"],
  districtPrimary: [
    "block",
    "min-w-0",
    "max-w-full",
    "truncate",
    "text-2xl",
    "font-extrabold",
    "tracking-tight",
    "leading-[1.2]",
    "text-[var(--text-main)]",
    "sm:text-4xl",
  ],
  districtSecondary: ["truncate", "text-sm", "font-medium", "text-[var(--text-sub)]"],
  districtDesktop: [
    "block",
    "min-w-0",
    "max-w-full",
    "truncate",
    "text-5xl",
    "font-extrabold",
    "tracking-tight",
    "leading-[1.3]",
    "text-[var(--text-main)]",
  ],
  districtFetching: [
    "animate-pulse",
    "transition-colors",
    "duration-300",
    "text-[var(--text-sub)]",
  ],
  refreshButton: ["shrink-0"],
  refreshIconLoading: ["animate-spin"],
  date: ["text-base", "text-[var(--text-sub)]", "md:text-xl"],
  weatherIcon: [
    "grid",
    "h-36",
    "w-36",
    "place-items-center",
    "rounded-full",
    "border",
    "border-[var(--line)]",
    "bg-[var(--surface-soft)]",
    "p-8",
    "text-[var(--text-main)]",
    "md:h-[4.25rem]",
    "md:w-[4.25rem]",
    "md:rounded-none",
    "md:border-0",
    "md:bg-transparent",
    "md:p-0",
    "md:text-[var(--icon-subtle)]",
  ],
  body: [
    "mt-8",
    "flex",
    "flex-col",
    "items-center",
    "gap-4",
    "text-center",
    "md:mt-14",
    "md:flex-row",
    "md:items-end",
    "md:gap-8",
    "md:text-left",
  ],
  currentTemp: [
    "text-8xl",
    "font-extrabold",
    "leading-none",
    "tracking-[-0.04em]",
    "text-[var(--text-main)]",
    "md:text-9xl",
  ],
  currentMeta: ["space-y-2", "pb-2"],
  currentSummary: ["text-2xl", "font-semibold", "text-[var(--text-main)]", "md:text-3xl"],
  currentFeelsLike: ["text-xl", "text-[var(--text-muted)]", "md:text-2xl"],
  divider: ["my-8", "h-px", "w-full", "bg-[var(--line)]", "md:my-10"],
  detailList: ["grid", "grid-cols-2", "gap-4", "md:grid-cols-3", "md:gap-6"],
  detailItem: ["flex", "items-center", "gap-3", "rounded-2xl", "px-1", "py-2", "md:gap-4"],
  detailIcon: ["text-[var(--icon-subtle)]"],
  detailText: ["flex", "flex-col", "gap-1"],
  detailLabel: [
    "text-xs",
    "font-bold",
    "tracking-[0.18em]",
    "text-[var(--text-muted)]",
    "uppercase",
    "md:text-sm",
  ],
  detailValue: ["text-2xl", "font-extrabold", "text-[var(--text-main)]", "md:text-3xl"],
} as const;

export const hourlyInfoCardStyles = {
  viewport: ["relative", "overflow-hidden"],
  wrapper: [
    "overflow-x-auto",
    "scrollbar-hide",
    "cursor-grab",
    "select-none",
    "active:cursor-grabbing",
    "-mx-4",
    "px-4",
  ],
  list: ["flex", "gap-3", "pb-1", "md:gap-4"],
  detail: [
    "flex",
    "w-28",
    "sm:w-32",
    "shrink-0",
    "flex-col",
    "items-center",
    "gap-3",
    "rounded-[1rem]",
    "border",
    "border-[var(--line)]",
    "bg-white",
    "px-5",
    "py-4",
    "transition-all",
    "duration-200",
    "hover:bg-[var(--surface-soft)]",
    "hover:shadow-sm",
  ],
  detailHour: [
    "text-base",
    "font-semibold",
    "tracking-tight",
    "text-[var(--text-sub)]",
    "whitespace-nowrap",
  ],
  detailIcon: ["text-[var(--icon-subtle)]"],
  detailValue: ["text-2xl", "font-extrabold", "leading-none", "text-[var(--text-main)]"],
  detailPrecipitation: [
    "inline-flex",
    "items-center",
    "gap-1",
    "max-w-full",
    "rounded-full",
    "px-2",
    "py-1",
    "text-xs",
    "font-bold",
    "leading-none",
  ],
  detailPrecipitationMuted: [
    "bg-[var(--surface-soft)]",
    "text-[var(--text-muted)]",
  ],
  detailPrecipitationLow: ["bg-[var(--color-blue-50)]", "text-[var(--color-blue-400)]"],
  detailPrecipitationMedium: ["bg-[var(--color-blue-100)]", "text-[var(--color-blue-600)]"],
  detailPrecipitationHigh: ["bg-[var(--color-blue-200)]", "text-[var(--color-blue-800)]"],
  loading: ["text-sm", "text-[var(--text-sub)]"],
  error: [
    "text-xl",
    "flex",
    "flex-col",
    "items-center",
    "justify-center",
    "gap-3",
    "md:gap-10",
    "md:flex-row",
  ],
};

export const favoritePreviewPanelStyles = {
  root: ["hidden", "min-w-0", "space-y-5", "lg:block"],
  header: ["flex", "items-center", "justify-between", "gap-3"],
  title: ["text-sm", "font-extrabold", "tracking-[0.18em]", "text-[var(--text-sub)]", "uppercase"],
  manageButton: ["px-2", "text-sm"],
  list: ["space-y-4"],
  card: [
    "w-full",
    "min-w-0",
    "rounded-[1.5rem]",
    "border",
    "border-[var(--line)]",
    "bg-white",
    "p-5",
    "cursor-pointer",
    "text-left",
    "shadow-sm",
    "transition",
    "hover:-translate-y-0.5",
    "hover:shadow-md",
    "focus-visible:outline-none",
    "focus-visible:ring-2",
    "focus-visible:ring-[var(--accent-soft)]",
  ],
  fetching: ["animate-pulse"],
  cardHeader: ["flex", "items-start", "justify-between", "gap-3"],
  cardTitle: ["truncate", "text-xl", "font-extrabold", "text-[var(--text-main)]"],
  cardLocation: ["mt-1", "truncate", "text-sm", "text-[var(--text-muted)]"],
  moreIcon: ["mt-1"],
  emptyCard: [
    "rounded-[1.5rem]",
    "border",
    "border-dashed",
    "border-[var(--line)]",
    "bg-white/70",
    "p-5",
    "text-center",
  ],
  emptyTitle: ["mt-3", "font-extrabold", "text-[var(--text-main)]"],
  emptyDescription: ["mt-1", "break-words", "text-sm", "leading-6", "text-[var(--text-sub)]"],
  addButton: [
    "flex",
    "w-full",
    "items-center",
    "justify-center",
    "gap-2",
    "rounded-[1.25rem]",
    "border",
    "border-dashed",
    "border-[var(--line)]",
    "bg-transparent",
    "px-5",
    "py-4",
    "cursor-pointer",
    "text-sm",
    "font-extrabold",
    "tracking-[0.08em]",
    "text-[var(--text-sub)]",
    "uppercase",
    "transition",
    "hover:bg-white",
  ],
} as const;

export const outfitRecommendationCardStyles = {
  root: ["min-w-0"],
  fetching: ["animate-pulse", "transition-opacity", "duration-300"],
  header: [
    "flex",
    "min-w-0",
    "flex-col",
    "gap-2",
    "md:flex-row",
    "md:items-start",
    "md:justify-between",
  ],
  eyebrow: [
    "text-xs",
    "font-extrabold",
    "tracking-[0.18em]",
    "text-[var(--text-muted)]",
    "uppercase",
  ],
  title: [
    "mt-2",
    "break-words",
    "text-2xl",
    "font-extrabold",
    "text-[var(--text-main)]",
    "md:text-3xl",
  ],
  summary: [
    "mt-3",
    "break-words",
    "text-base",
    "leading-7",
    "text-[var(--text-sub)]",
    "md:text-lg",
  ],
  basis: [
    "shrink-0",
    "rounded-full",
    "bg-[var(--surface-soft)]",
    "px-3",
    "py-1",
    "text-xs",
    "font-semibold",
    "text-[var(--text-muted)]",
  ],
  chipList: ["mt-5", "flex", "min-w-0", "flex-wrap", "gap-2"],
  chip: [
    "max-w-full",
    "break-words",
    "rounded-full",
    "bg-[var(--surface-soft)]",
    "px-3",
    "py-2",
    "text-sm",
    "font-bold",
    "text-[var(--text-main)]",
  ],
  cautionBox: [
    "mt-5",
    "space-y-2",
    "rounded-2xl",
    "bg-[var(--surface-soft)]",
    "p-4",
    "text-sm",
    "leading-6",
    "text-[var(--text-sub)]",
  ],
  cautionTitle: ["font-extrabold", "text-[var(--text-main)]"],
  cautionList: ["list-disc", "space-y-1", "pl-5"],
  cautionItem: ["break-words"],
  skeletonHeader: ["space-y-3"],
  skeletonChipList: ["mt-5", "flex", "flex-wrap", "gap-2"],
} as const;
