export const searchPageStyles = {
  page: ["flex", "w-full", "self-start", "flex-col"],
  stackItem: ["mt-6", "md:mt-8"],
  searchWrap: [
    "rounded-2xl",
    "border",
    "border-[var(--line)]",
    "bg-white",
    "shadow-sm",
    "md:rounded-[1.5rem]",
  ],
  searchInput: [
    "w-full",
    "rounded-xl",
    "bg-[var(--surface)]",
    "px-4",
    "py-3",
    "text-sm",
    "outline-none",
    "ring-[var(--accent)]",
    "transition",
    "focus:ring-2",
  ],
  section: ["rounded-2xl", "border", "border-[var(--line)]", "bg-white", "p-4", "shadow-sm"],
  sectionGroup: ["space-y-4"],
  sectionTitle: [
    "text-sm",
    "font-extrabold",
    "tracking-[0.18em]",
    "text-[var(--text-sub)]",
    "uppercase",
  ],
  candidate: [
    "flex",
    "items-center",
    "justify-between",
    "gap-3",
    "rounded-2xl",
    "border",
    "border-[var(--line)]",
    "bg-white",
    "p-4",
    "shadow-sm",
    "transition",
    "cursor-pointer",
    "hover:shadow-md",
  ],
  candidateContent: ["min-w-0", "truncate", "flex-1", "cursor-pointer"],
  candidateName: ["text-sm", "font-semibold", "text-[var(--text-main)]"],
  candidateHighlight: ["text-sm", "font-bold", "text-[var(--accent)]"],
  recentList: ["space-y-3"],
  recentItem: [
    "flex",
    "w-full",
    "items-center",
    "justify-between",
    "gap-3",
    "rounded-2xl",
    "border",
    "border-[var(--line)]",
    "bg-white",
    "p-4",
    "cursor-pointer",
    "text-left",
    "shadow-sm",
    "transition",
    "hover:shadow-md",
  ],
  recentNavigateButton: [
    "flex",
    "min-w-0",
    "flex-1",
    "cursor-pointer",
    "items-center",
    "justify-between",
    "gap-3",
    "text-left",
  ],
  recentText: ["flex", "min-w-0", "flex-col", "gap-1"],
  recentArrow: ["shrink-0", "text-xl", "text-[var(--text-sub)]"],
  recentDeleteButton: [
    "inline-flex",
    "h-9",
    "w-9",
    "shrink-0",
    "cursor-pointer",
    "items-center",
    "justify-center",
    "rounded-full",
    "text-[var(--text-sub)]",
    "transition",
    "hover:bg-[var(--surface-soft)]",
    "hover:text-[var(--text-main)]",
    "focus-visible:outline-2",
    "focus-visible:outline-offset-2",
    "focus-visible:outline-[var(--accent)]",
  ],
  mapMotionSlot: [
    "overflow-hidden",
    "transition-all",
    "duration-300",
    "ease-out",
    "will-change-[max-height,opacity,transform,margin]",
    "motion-reduce:transform-none",
    "motion-reduce:transition-none",
  ],
  mapMotionSlotOpen: ["mt-6", "max-h-[22rem]", "translate-y-0", "opacity-100", "md:mt-8"],
  mapMotionSlotClosed: ["mt-0", "max-h-0", "-translate-y-3", "opacity-0", "pointer-events-none"],
  mapCanvas: ["h-[21.875rem]"],
} as const;
