export const searchPageStyles = {
  page: ["space-y-6", "md:space-y-8"],
  searchWrap: [
    "rounded-2xl",
    "border",
    "border-[var(--line)]",
    "bg-white",
    "shadow-sm",
    "md:rounded-[1.5rem]",
  ],
  searchInput: [
    "w-full",
    "rounded-xl",
    "bg-[var(--surface)]",
    "px-4",
    "py-3",
    "text-sm",
    "outline-none",
    "ring-[var(--accent)]",
    "transition",
    "focus:ring-2",
  ],
  section: ["rounded-2xl", "border", "border-[var(--line)]", "bg-white", "p-4", "shadow-sm"],
  sectionGroup: ["space-y-4"],
  sectionTitle: [
    "text-sm",
    "font-extrabold",
    "tracking-[0.18em]",
    "text-[var(--text-sub)]",
    "uppercase",
  ],
  candidate: [
    "flex",
    "items-center",
    "justify-between",
    "gap-3",
    "rounded-2xl",
    "border",
    "border-[var(--line)]",
    "bg-white",
    "p-4",
    "shadow-sm",
    "transition",
    "cursor-pointer",
    "hover:shadow-md",
  ],
  candidateContent: ["min-w-0", "truncate", "flex-1", "cursor-pointer"],
  candidateName: ["text-sm", "font-semibold", "text-[var(--text-main)]"],
  candidateHighlight: ["text-sm", "font-bold", "text-[var(--accent)]"],
  recentList: ["space-y-3"],
  recentItem: [
    "flex",
    "w-full",
    "items-center",
    "justify-between",
    "gap-3",
    "rounded-2xl",
    "border",
    "border-[var(--line)]",
    "bg-white",
    "p-4",
    "text-left",
    "shadow-sm",
    "transition",
    "hover:shadow-md",
  ],
  recentText: ["flex", "min-w-0", "flex-col", "gap-1"],
  recentArrow: ["shrink-0", "text-xl", "text-[var(--text-sub)]"],
  mapCtaCard: [
    "relative",
    "block",
    "min-h-48",
    "w-full",
    "overflow-hidden",
    "rounded-[1.5rem]",
    "border",
    "border-[var(--line)]",
    "bg-white",
    "shadow-sm",
  ],
  mapTexture: [
    "absolute",
    "inset-0",
    "bg-[linear-gradient(90deg,rgba(255,255,255,0.88),rgba(255,255,255,0.2),rgba(255,255,255,0.88)),repeating-linear-gradient(0deg,#e9eef5_0,#e9eef5_1px,transparent_1px,transparent_18px),repeating-linear-gradient(90deg,#e9eef5_0,#e9eef5_1px,transparent_1px,transparent_18px)]",
  ],
  mapButton: [
    "absolute",
    "left-1/2",
    "top-1/2",
    "-translate-x-1/2",
    "-translate-y-1/2",
    "rounded-full",
    "bg-white",
    "px-6",
    "py-3",
    "text-sm",
    "font-extrabold",
    "text-[var(--text-main)]",
    "shadow-md",
  ],
} as const;
