export const NO_DATA_STATUS_CODE = {
  WEATHER_NOW: "MWB-NODATA-KMA-NOW",
  WEATHER_HOURLY: "MWB-NODATA-KMA-HOURLY",
  WEATHER_PRECIPITATION: "MWB-NODATA-KMA-POP",
  WEATHER_WIND: "MWB-NODATA-KMA-WIND",
  WEATHER_OUTFIT: "MWB-NODATA-KMA-OUTFIT",
  BOOKMARK_CURRENT: "MWB-NODATA-KMA-BOOKMARK-CURRENT",
  BOOKMARK_PREVIEW: "MWB-NODATA-KMA-BOOKMARK-PREVIEW",
  AIR_QUALITY_PM10: "MWB-NODATA-AIRKOREA-PM10",
  AIR_QUALITY_PM25: "MWB-NODATA-AIRKOREA-PM25",
  SUNRISE_SUNSET: "MWB-NODATA-KASI-SUN",
} as const;

export type NoDataStatusCode = (typeof NO_DATA_STATUS_CODE)[keyof typeof NO_DATA_STATUS_CODE];
